# Site settings
title: Live Stream Notifier for Firefox
email: martin@humanoids.be
description: > # this means to ignore newlines until "baseurl:"
  Live Stream Notifier is a Firefox extension, which notifies you, whenever a
  followed Streamer goes live. It features advanced control over the channels
  it monitors and a panel for quick access to those channels.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jtvn.humanoids.be" # the base hostname & protocol for your site
twitter_username: freaktechnik
github_username:  freaktechnik/justintv-stream-notifications
amo_slug: justintv-stream-notificatio

defaults:
  -
    scope:
      path: "changes"
      type: "pages"
    values:
      layout: "changes"
      group: "changes"

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: pygments
